### PR TITLE
Add Newsubtype

### PR DESCRIPTION
**Pull request by jabrouwer82**
Hey, not sure how open you are to scope creep in the first day, but here's an implementation of newsubtype to match your newtype. I'm not exactly confident in my scala 2 implementation, I relied heavily on the tests to validate it.

### CODE REVIEW

**Comment by alexandru** [comment]
Pretty cool — I'm digesting it and will be back.

Thinking of what to do with all the code repetition. But maybe it's fine.

**Comment by alexandru** [comment]
Test is failing.

**Comment by jabrouwer82** [comment]
I agree about the code duplication, this involved fair amount of copy/paste. I don't have any suggestions to help though.

I have a fix for the docs that I'll push if the other tests can get sorted out, though it feels a bit weird since I think the examples need to coexist. I had to define `NonEmptyListSub` and similar, so they wouldn't collide with the `NewtypeK` example.

I think I was mistakenly running the tests on scala 3.0.2 rather than 3.0.1. It works in 3.0.2 and I have absolutely no idea why it doesn't work on 3.0.1. Plus [#12815](https://github.com/lampepfl/dotty/pull/12815) shipped with 3.0.2.

**Comment by alexandru** [comment]
Update Scala to 3.0.2 ... needs to be updated in `.github/workflows/build.yml`.

**Comment by jabrouwer82** [comment]
I wouldn't approve that workflow, it's just the github fork merge. I'll post a comment when this branch is good to go from my end.

**Comment by jabrouwer82** [comment]
Alright, I think that one should work.

**Pull request merged**
